### ISSUE TITLE
Make clear that "browse" is also "add post", maybe browse&add? 

### ISSUE THREAD

**Issue by Locusto** [LucNaterop/tauschhandel#10]

**Comment by Locusto** [comment]
will s checked vilich nöd all, dass de plus button für neui posts sind und s isch ja essenziell, dass lüt züg uploaded

**Comment by lucnat** [comment]
Ich wür sege de Tab söll heisse "Browse / Add". Was meineder?

**Comment by Locusto** [comment]
top

**Comment by lucnat** [comment]
Das wür denn folgendermasse usgseh: 

![tab bild](http://i.imgur.com/9xCLJQa.jpg)

Also machi grad.

**Comment by Locusto** [comment]
perfekt dude
