### ISSUE TITLE
Phone-back-button problem persisting

### ISSUE THREAD

**Issue by Locusto** [LucNaterop/tauschhandel#12]
Vilich isch das s gliche Problem, aber mer chunnt ez zwar us zB eme neue post oder eim womer bearbeited use, aber susch funktioniert de back button nöd, mer mun immer de vom app benutze. chasch das ändere?

**Comment by lucnat** [comment]
Oh ja, das isch en Fehler i de implementierig gsi vo mir. Es sött jetzt soo sii, dass de backbutton überall funktioniert PLUS modals vo new post und filter schlüsse chan. Chasch das bestätige?
