### ISSUE TITLE
Collabsable Tabs    + Placeholder

### ISSUE THREAD

**Issue by laserflip** [LucNaterop/tauschhandel#15]
Collabsable tabs with number of posts in brackets:  Männedorf (4)        <-

--------> dann keine verwirrung mehr wenn placeholder nur bei homegemeinde

-----> Wie funktionierts mit em merke vom state (collapsed or not collapsed)? Sött das nür für jedi session gpseicheret werde oder permanent?

**Comment by lucnat** [comment]
Ja, das wird jetzt inere session gspeicheret. Session('collapsed') isch es array vo postleitzahle wo collapsed sind.
