### ISSUE TITLE
Camera Upload problem

### ISSUE THREAD

**Issue by Locusto** [LucNaterop/tauschhandel#5]
Camera-Upload dreiht um 90 Grad, egal ob Profilpicture oder Post-Picture, mengisch nach links, mengisch nach rechts

**Comment by lucnat** [comment]
Machts en Unterschied wenn du de Upload us de gallery machsch?

**Comment by Locusto** [comment]
Also bim Profile-Picture machts kein Unterschied, det dreihts uf beidi Arte. Struberwiis ischs bimne neue post andersch; dete dreihts die wod vo de camera machsch, aber gallery uploads nöd :O

**Comment by lucnat** [comment]
WOOOOOOOOOOOT

**Comment by Locusto** [comment]
I swear, aber probieres nomal

**Comment by Locusto** [comment]
OMG, hans checkt!

zumindest wennd es bild vo de gallery nimsch, dreihts es nume, wenns hochkant ufgno worde isch!! nöd, wenns quer fotografiert worde isch!!!!

**Comment by Locusto** [comment]
YESS, SGLICHE ISCH BIM PROFILE PIC SPROBLEM!!!

**Comment by Locusto** [comment]
wenns quer ufgno worde isch oder i quer i de library isch, denn chunnt s richtig ume ine. nume hochkant isch s problem!!

**Comment by lucnat** [comment]
Ok. Ich han ehrlichgseit kei idee wie ich das problem chönnti aaga. Gseht grad recht schlecht us für image upload bi android..........

**Comment by Locusto** [comment]
fuck, ez hani gmeint, ich heg de weg zu de lösig gfunde ^^

aber isch das problem denn teil vom upload feature, das hesch ja wahrsch nöd selber coded, oder?

**Comment by lucnat** [comment]
Ja ebe, das isch s problem. Dä part chan ich gar nöd beiiflusse. S android betriebssystem git mim app im prinzip eifach es bild. Und ich chan nöd usefinde, öb das richtig drület isch oder nöd.

**Comment by Locusto** [comment]
https://github.com/samayo/bulletproof/issues/39

vilich hilft das?

**Comment by lucnat** [comment]
Das isch seeeehr nützlich
