### ISSUE TITLE
Back Button problem

### ISSUE THREAD

**Issue by Locusto** [LucNaterop/tauschhandel#6]
wemmer es pop up fenster wie zB "neue post" oder oder "filter" öffnet, chamer mitm "phone-back-button" nöd zrug, sondern muss ufs chrüzli oder de pfiil-zrug im pop-up drucke. Isch das sgliche Problem? will s problem isch, dass s app denn im hintergrund zrugg gaht, aber s pop up blibt divorne

**Comment by lucnat** [comment]
Da d lösig z müesam isch, existiert de back button jetzt nur no bi de chats.
