### ISSUE TITLE
Editing of posts problem 

### ISSUE THREAD

**Issue by Locusto** [LucNaterop/tauschhandel#8]
wenn mer en post am bearbeite isch und dtastatur no offe isch, während mer uf add picture druckt, gaht zersch d tastatur zue und mer muess nomal drucke

**Comment by Locusto** [comment]
aber das isch eich nöd schlimm

**Comment by lucnat** [comment]
Das wird vom betriebssystem ghandlet... Da chan ich echt nix mache. De erscht klick isch schlüsse vode tastatur.
